### ISSUE TITLE
Gradient Slider not working in absolute positioned ColorPicker

### ISSUE THREAD

**Issue by Arif-un** [arthay/react-color-gradient-picker#2]
Hi there,
I found this library for gradient/color picker. It's a great library for solid and gradient color and it's fast and lightweight with a good output value.
Recently I used it in one of my projects and found this issue when I set this picker in absolute positioned popup div.

Thanks.

**Comment by arthay** [comment]
Hi @Arif-un. Thanks for your opened issue.
Can you provide a video about this issue. I can not reproduced this issue. Thank you.

**Comment by Arif-un** [comment]
Solved, After wrap absolute positioned div in a relative positioned div,

**Comment by robba86** [comment]
Im having this problem to. Having colorpicker inside a div with position: fixed. When i scroll down a bit, it does not pinpoint the color when im selecting it from the colorpicker.
